# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6882f30313817b07cb74e89aa31bc2db9c3a9724dde89659b8f8c5a84821b757c0fa2d5db968be15fab22ee8b36e0e4e3621073eddd1a49358b69b57ed2b1ba5

test:
  secret_key_base: f205a0aad8b1cad7796de5ac5cc7d6b016c6b24133220f436b866a3828ee1b56e50bba351bb014d88978b1d502aab4a09b0a18d27b99490b747994dbf5d25e63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
